cronJobs:
  CHECK:
    command: "just check"
    envSecrets:
    - secret-envs
    envConfigmaps:
    - envs
  check2:
    name: check22
    command: "just check2"
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
