pdbs:
  pdb1:
    labels:
      foo: bar
    minAvailable: 1
    maxUnavailable: 2
    extraSelectorLabels:
      foo: bar
  PDB2:
    labels:
      bar: foo
    maxUnavailable: 2
    extraSelectorLabels:
      bar: foo
