servicemonitors:
  mysm:
    endpoints:
    - interval: 30s
      port: exporter
      path: /metrics
    extraSelectorLabels:
      app: nginx
    labels:
      foo: foo
  sm2:
    endpoints:
    - interval: 30s
      port: exporter
      path: /metrics
    namespaceSelector:
      any: true
  SM3:
    endpoints:
    - interval: 30s
      port: exporter
      path: /metrics
    namespaceSelector:
      matchNames:
        - production
